---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk-alpine'

inputs:
  - name: source-code

outputs:
  - name: build-output

run:
  path: source-code/org.makro.spring.restapi.general/ci/build.sh
